CREATE DATABASE IF NOT EXISTS Maria;

USE Maria;

CREATE TABLE IF NOT EXISTS Users (
   id INT PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(50),
   pass VARCHAR(50)
);

INSERT INTO Users (username, pass) VALUES ('qwer', 'qwer');

CREATE TABLE IF NOT EXISTS Images (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    file_name VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

SELECT * FROM Images;
SELECT * FROM Users;

DELETE FROM Images;