CREATE DATABASE IF NOT EXISTS Maria;

USE Maria;

CREATE TABLE IF NOT EXISTS Users (
   id INT PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(50),
   pass VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Images (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    caption VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

SELECT * FROM Images;
SELECT * FROM Users;

DELETE FROM Images;

DROP TABLE Images;
DROP TABLE users;